[package]
name = "landro-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "landropic"
path = "src/main.rs"

[dependencies]
landro-daemon = { path = "../landro-daemon" }
landro-crypto = { path = "../landro-crypto" }

clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
indicatif = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }