[build]
# Use all available CPU cores for compilation
# jobs = 0  # 0 means use all cores, but some versions don't support this
# Build cache configuration for faster rebuilds
pipelining = true

# Use faster linker on macOS (since you're on darwin)
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/ld"]

[target.aarch64-apple-darwin] 
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/ld"]

# Faster compilation with share-generics
[unstable]
share-generics = true

# Enable faster builds with sparse registry
[registries.crates-io]
protocol = "sparse"